data:
  catalog: shm
  schema: noc_agent
  raw_data_volume: raw_data
  product_tables:
    "14100320": monthly_hours_and_wages
    "14100310": monthly_adjusted_employment_by_occupation
    "14100421": monthly_labour_force_characteristics
    "14100425": monthly_job_tenure_by_occupation
  pdfs: 
    NOC: https://www.statcan.gc.ca/en/12-583-x/12-583-x2021001-eng.pdf
agent:
  streaming: False
  model_name: noc_agent
model:
  endpoint_name: databricks-meta-llama-3-3-70b-instruct
  parameters:
    temperature: 0
    max_tokens: 400
retriever:
  endpoint_name: one-env-shared-endpoint-3
  index_name: noc_index
  source_table: noc_chunks_clean
  embedding_model: databricks-gte-large-en
  parameters:
    score_threshold: 0
    k: 3
    query_type: ann
