# Application configuration
title: NOC Agent
description: Get your NOC classification and a report on your occupation outlook
example: I am a haul truck driver working in the oil and gas industry, can you prepare an occupation report for the past 12 months?
serving_endpoint: agents_shm-noc_agent-noc_agent
